// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DES_AR201154_RM220242_VM220243_Desafio1.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DES_AR201154_RM220242_VM220243_Desafio1.Models.Departamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripcion = "Gestiona el personal de la empresa.",
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            ID = 2,
                            Descripcion = "Desarrollo y mantenimiento de sistemas.",
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            ID = 3,
                            Descripcion = "Encargado de la comercialización de productos.",
                            Nombre = "Ventas"
                        });
                });

            modelBuilder.Entity("DES_AR201154_RM220242_VM220243_Desafio1.Models.Empleado", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartamentoID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("DepartamentoID");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartamentoID = 1,
                            Descripcion = "Empleado con experiencia en RRHH.",
                            FechaContratacion = new DateTime(2010, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1985, 5, 20),
                            Nombre = "John Doe",
                            Salario = 50000m
                        },
                        new
                        {
                            ID = 2,
                            DepartamentoID = 2,
                            Descripcion = "Desarrolladora de software senior.",
                            FechaContratacion = new DateTime(2015, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1990, 3, 10),
                            Nombre = "Jane Smith",
                            Salario = 70000m
                        },
                        new
                        {
                            ID = 3,
                            DepartamentoID = 3,
                            Descripcion = "Especialista en ventas y marketing.",
                            FechaContratacion = new DateTime(2012, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1982, 11, 22),
                            Nombre = "Mark Johnson",
                            Salario = 55000m
                        },
                        new
                        {
                            ID = 4,
                            DepartamentoID = 1,
                            Descripcion = "Gerente de Recursos Humanos.",
                            FechaContratacion = new DateTime(2005, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1978, 7, 30),
                            Nombre = "Emily Davis",
                            Salario = 75000m
                        },
                        new
                        {
                            ID = 5,
                            DepartamentoID = 2,
                            Descripcion = "Ingeniero de soporte técnico.",
                            FechaContratacion = new DateTime(2020, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaNacimiento = new DateOnly(1995, 12, 5),
                            Nombre = "Michael Brown",
                            Salario = 60000m
                        });
                });

            modelBuilder.Entity("DES_AR201154_RM220242_VM220243_Desafio1.Models.Empleado", b =>
                {
                    b.HasOne("DES_AR201154_RM220242_VM220243_Desafio1.Models.Departamento", "Departamento")
                        .WithMany("Empleado")
                        .HasForeignKey("DepartamentoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("DES_AR201154_RM220242_VM220243_Desafio1.Models.Departamento", b =>
                {
                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
